# Generated by Django 4.0.6 on 2022-08-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_text'),
        ('blog', '0003_alter_post_id'),
    ]

    operations = [
    ]
